version: "3.8"

services:
  backend:
    build: ./server  # Path to backend code
    ports:
      - "5001:5001"  # Map port 5001 of the container to 5001 on the host
    env_file:
      - ./server/.env  # Load environment variables for backend
    depends_on:
      - mongo  # Ensure MongoDB starts before the backend
    networks:
      - app_network
    restart: unless-stopped # Restart unless manually stopped

  frontend:
    build: ./client  # Path to frontend code
    ports:
      - "80:80"  # Serve frontend on port 80 using Nginx
    depends_on:
      - backend  # Ensure backend starts before frontend
    networks:
      - app_network
    restart: unless-stopped # Automatically restarts unless manually stopped

  mongo:
    image: mongo:latest  # Official MongoDB image
    container_name: mongo_db
    restart: unless-stopped
    env_file:
      - ./server/.env  # Load MongoDB credentials from environment file
    ports:
      - "27017:27017"  # Expose MongoDB for development access
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    networks:
      - app_network

volumes:
  mongo_data:  # Persistent storage for MongoDB

networks:
  app_network:  # Custom network for inter-service communication
