version: '3.9'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000" # Expose your server's port
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017" # MongoDB port
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
