version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - app_network
    restart: unless-stopped
    
  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

  mongo:
    image: mongo:6.0  # Official MongoDB image
    container_name: mongo_db
    restart: unless-stopped
    env_file:
      - ./server/.env  # Load MongoDB credentials from environment file
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    networks:
      - app_network

volumes:
  mongo_data:  # Persistent storage for MongoDB

networks:
  app_network:  # Custom network for inter-service communication
